all: version1 version2 version3 version4
version1:version1.c
	gcc -o version1 version1.c
version2:version2.c
	gcc -o version2 version2.c -lpthread
version3:version3.c
	gcc -o version3 version3.c
version4:version4.c
	gcc -o version4 version4.c